In [2]:
import numpy as np 
from sklearn.datasets import make_regression , load_diabetes
import matplotlib.pyplot as plt

In [3]:
x, y = load_diabetes(return_X_y=True)

In [40]:
class MyRidge:
    def __init__(self, lr, epoch):
        self.lr = lr
        self.epoch = epoch
    
    def fit (self , x_t , y_t):
        n_samples , n_features = x_t.shape
        
        # bais column [1, ]
        x_b = np.c_[np.ones(n_samples), x_t]
        
        # intialize weights 
        self.theta = np.zeros(n_features + 1)
        
        for _ in range(self.epoch):
            y_pred = x_b @ self.theta
            error = y_pred - y_t
            
            grad = (2 / n_samples) * (x_b.T @ error)
            self.theta -= self.lr * grad
        
        self.intercept_ = self.theta[0]
        self.coeff_ = self.theta[1:]
        
        return self 
    
    def predict(self, x):
        x_b = np.c_[np.ones(x.shape[0]), x]
        return x_b @ self.theta

In [7]:
data = load_diabetes()

In [10]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

In [4]:
from sklearn.model_selection import train_test_split
x_t, x_tt , y_t , y_tt = train_test_split(x, y, test_size=.2)

In [23]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01, solver='cholesky')


In [28]:
ridge.fit(x_t, y_t)


Ridge(alpha=0.01, solver='cholesky')

In [29]:

ridge.coef_, ridge.intercept_

(array([ -45.00983078, -277.59036022,  523.36879896,  343.99762055,
        -347.71160144,   97.16694738,  -59.70001572,  100.33425064,
         642.97588127,   73.11111469]),
 153.5430551991991)

In [30]:
# Correct usage: pass x_tt directly, not [x_tt]
predictions = ridge.predict(x_tt)
predictions

array([157.01184043, 178.49047341, 213.43093841,  94.80717953,
       137.47655784, 114.24875971,  81.42130274, 191.12441454,
       239.25497709, 146.49017542, 132.69022591, 195.48227858,
       106.28204431,  62.81916891, 215.76651059, 123.19508341,
       127.29829925, 192.90482094,  72.09902312, 164.61489931,
       103.87364695, 122.2597666 , 199.10362262, 170.1399798 ,
       231.5543729 , 119.14743487, 171.09762004, 184.64834173,
        81.85145278, 110.34907524, 259.07731418,  75.59890703,
       214.82636125, 104.99993763,  97.3949226 , 199.70680497,
       193.81625659, 224.93536173, 212.38957216, 244.28027035,
       178.23549212, 204.60777993, 160.45928392,  64.51053834,
       236.7102062 , 164.79644609, 148.58135599,  88.28702563,
       269.45984944,  58.50920729, 165.21338365, 305.47937756,
       184.00274672,  88.32039266,  72.01741584, 176.97480061,
       190.54820642, 141.42728779,  89.95422964, 239.34623851,
       209.7980761 , 112.83179792, 171.2214303 , 217.03

In [31]:
from sklearn.metrics import r2_score
r2_score(y_tt, predictions)

0.43093360340315245

In [ ]:
class MeraRidge:
    
    def __init__(self,alpha=0.1):
        
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        
        X_train = np.insert(X_train,0,1,axis=1)
        I = np.identity(X_train.shape[1])
        I[0][0] = 0
        result = np.linalg.inv(np.dot(X_train.T,X_train) + self.alpha * I).dot(X_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [33]:
r2 = MeraRidge()
r2.fit(x_tt, y_tt)
r2.coef_, r2.intercept_

(array([ 106.93243957,  -55.15050728,  403.70840902,  165.0055795 ,
          -4.10105997,   11.01640761, -243.80371455,  169.45424334,
         258.5262252 ,   83.43204819]),
 147.0214421215774)

In [34]:
pred_y = r2.predict(x_tt)
pred_y

array([154.16987943, 155.47569429, 215.68796985, 111.79405635,
       126.70561635, 157.61938953,  91.72139327, 187.92800341,
       194.65958724, 161.80564187, 129.2222404 , 172.99419739,
        97.71698627,  57.61320099, 181.53261966, 107.92391185,
       113.03206243, 194.00202346,  87.75929845, 154.28600691,
       161.93261713,  91.20985003, 203.03139   , 170.07222414,
       217.33517439, 148.67155734, 176.19314009, 158.25211492,
        81.09189877, 134.27057107, 209.50054534,  91.22717255,
       226.07910843, 134.51428473,  86.35870195, 194.88805462,
       146.344135  , 195.24606287, 190.7372197 , 205.96693626,
       188.86151031, 179.23468619, 141.55450371,  68.57986076,
       180.62516133, 179.65379168, 123.98430047,  89.17230034,
       226.8030749 ,  51.7623716 , 148.83115856, 243.72995582,
       167.58588899, 108.20697142,  73.78863287, 169.39734147,
       165.63388572, 140.01072269,  88.07543423, 198.24128762,
       182.70714468, 105.24236414, 188.12808313, 164.57

In [36]:
r2_score(y_tt, pred_y)


0.4893399579625759

In [60]:
r3 = MyRidge(.01, 100000)
r3.fit(x_t, y_t)
r3.coeff_ , r3.intercept_

(array([ -41.25260152, -278.19476583,  528.77963551,  344.1409163 ,
         -58.01796597, -147.83594502, -173.70163812,   99.57779782,
         508.91547328,   86.82191017]),
 153.51879234491494)

In [61]:
ored = r3.predict(x_tt)

In [62]:
r2_score(y_tt, ored)

0.43235212755599395